name: Android CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: brew install ktlint
      - name: run ktlint
        run: |
          ktlint --reporter=checkstyle,output=build/ktlint-report.xml
      - uses: yutailang0119/action-ktlint@v1.0.0
        with:
          xml_path: build/*.xml
      - name: Build android app
        run: ./gradlew assembleDebug
      - name: Run Unit Tests
        run: ./gradlew test
#      - name: Build iOS shared code
#        run: ./gradlew :common:compileKotlinIOS